#ifndef vm_public_h
#define vm_public_h

enum {
    TRAP_API_LOADSCRIPTBYNAME,
    TRAP_BINDRENDERTEXTURE,
    TRAP_CON_ERROR,
    TRAP_CON_PRINTF,
    TRAP_CONNECTSERVICE,
    TRAP_CREATEMODEL,
    TRAP_CREATERECTANGLEMODEL,
    TRAP_CREATERENDERTEXTURE,
    TRAP_DOMAIN_ACQUIREOBJECTHANDLE,
    TRAP_DOMAIN_GETLUASTATE,
    TRAP_DOMAIN_GETMETRICS,
    TRAP_DOMAIN_GETRENDERER,
    TRAP_DRAWDEBUGSTATS,
    TRAP_DRAWENTITY,
    TRAP_DRAWLINES,
    TRAP_GETIMAGEINFO,
    TRAP_GETPIPELINESTATE,
    TRAP_GETTEXTHEIGHT,
    TRAP_GETTEXTINSETS,
    TRAP_GETTEXTWIDTH,
    TRAP_LOADSHADER,
    TRAP_OBJECT_GETMETRICS,
    TRAP_OBJECT_GETRENDERER,
    TRAP_PRINTTEXT,
    TRAP_RELEASESERVICE,
    TRAP_SETDEFAULTPIPELINESTATE,
    TRAP_SETPIPELINESTATE,
    TRAP_SYS_MILLISECONDS,
};

#endif
